Review readme
SkylineCommunications/chat-integration pull request #12
Opened 2022-08-31 12:33 UTC by MariekeGO

2022-08-31 14:00 UTC, RobbertVH approved these changes

2022-09-01 06:04 UTC, JordyGit requested changes

2022-09-01 06:04 UTC, JordyGit commented on README.md
> +3. Click the '*execute now*' button.  A team (with a General channel) will be created in Microsoft Teams, if the [DataMiner bot](https://teams.microsoft.com/l/app/9a09d087-5d07-4481-b34f-cd053eab7925
The bot doesn't create the team, our api (called from this automation script) is creating the team with the microsoft graph api, and is directly installing our bot also in the team. We do this so we can send the notifications using our bot.

2022-09-01 06:04 UTC, JordyGit commented on README.md
> +2. Fill in the necessary information. Note that the **the fields are case sensitive**.
2 times 'the'

2022-09-01 06:04 UTC, JordyGit commented on README.md
> +2. Fill in the necessary information. Note that the **the fields are case sensitive**.
in all examples :)

2022-09-01 06:10 UTC, JordyGit approved these changes

2022-09-01 06:11 UTC, merged